# Generated by Django 4.2.13 on 2024-09-22 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_conversation_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 22, 18, 50, 30, 583801, tzinfo=datetime.timezone.utc)),
        ),
    ]
