# Generated by Django 4.2.13 on 2024-09-23 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_conversation_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 23, 3, 59, 44, 604779, tzinfo=datetime.timezone.utc)),
        ),
    ]
