# Generated by Django 4.2.13 on 2024-09-23 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_alter_conversation_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 23, 4, 2, 59, 581547, tzinfo=datetime.timezone.utc)),
        ),
    ]
