# Generated by Django 4.2.13 on 2024-09-23 04:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_alter_conversation_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
