# Generated by Django 4.2.16 on 2024-10-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_alter_conversation_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='references',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
