# Generated by Django 4.2.16 on 2024-10-27 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_message_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='message',
            name='metrics',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
