# Generated by Django 4.2.13 on 2024-07-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('metadata', models.JSONField()),
            ],
        ),
    ]
