# Generated by Django 4.2.13 on 2024-09-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='filename',
            field=models.TextField(default=None, null=True),
        ),
    ]
