# Generated by Django 4.2.13 on 2024-09-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest_data', '0002_law_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='filename',
            field=models.TextField(),
        ),
    ]
