# Generated by Django 4.2.16 on 2025-05-11 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digest_data', '0003_alter_law_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fragment_number', models.IntegerField()),
                ('content', models.TextField()),
                ('law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='digest_data.law')),
            ],
            options={
                'unique_together': {('fragment_number', 'law')},
            },
        ),
    ]
