# Generated by Django 4.2.16 on 2025-05-23 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digest_data', '0004_textchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='law',
            name='proccessed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='law',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='textchunk',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textchunk',
            name='proccessed',
            field=models.BooleanField(default=False),
        ),
    ]
