upstream chatbot {
    server django-server:8000;
}

# Redirect HTTP to HTTPS
server {
    listen 80;
    server_name digestogpt.works;
    return 301 https://$host$request_uri;
}

# HTTPS server
server {
    listen 443 ssl;
    server_name digestogpt.works;

    ssl_certificate     /etc/nginx/certs/digestogpt.works.fullchain.crt;
    ssl_certificate_key /etc/nginx/certs/digestogpt.works.key;

    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://chatbot;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /static/ {
        alias /home/app/static/;
    }
}
