upstream chatbot {
    server django-server:8000;
}

server {
    listen 80;

    location / {
        proxy_pass http://chatbot;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host; # Optional, but often needed
    }

    location /static/ {
        alias /home/app/static/;
    }
}
